name: Build Google Font variant

on: [push, release]

env:
  GF_RELEASE_DIR: /tmp/build_gf
  GF_ASSET_FILENAME: ChironHeiHK-GoogleFonts.zip

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Wellcome
        run: mkdir -p $GF_RELEASE_DIR
      - name: Create directory
        run: mkdir -p $GF_RELEASE_DIR
      - name: Create file 1
        run: echo "Hello" > $GF_RELEASE_DIR/file1.txt
      - name: Create file 2
        run: echo "Hello" > $GF_RELEASE_DIR/file2.txt
      - name: ls
        run: ls -l $GF_RELEASE_DIR
      - uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: gf-built-fonts
          path: ${{ env.GF_RELEASE_DIR }}

  release:
    if: github.event_name == 'release'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          name: gf-built-fonts
          path: ${{ env.GF_RELEASE_DIR }}
      - name: Zip files
        run: zip -r $GF_ASSET_FILENAME $GF_RELEASE_DIR
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.GF_ASSET_FILENAME }}
          asset_name: $GF_ASSET_FILENAME
          tag: ${{ github.ref }}
          overwrite: true
          body: "Google Font variant built from commit ${{ github.sha }}."